"""Add transacted_only column to cycle_counts

Revision ID: 147f02641400
Revises: 
Create Date: 2025-11-30 18:16:13.041613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '147f02641400'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cycle_counts', sa.Column('transacted_only', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_user_groups_updated_by_id_users'), 'user_groups', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_groups_created_by_id_users'), 'user_groups', type_='foreignkey')
    op.alter_column('user_groups', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('user_groups', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_constraint(op.f('fk_user_group_members_created_by_id_users'), 'user_group_members', type_='foreignkey')
    op.drop_constraint(op.f('fk_user_group_members_updated_by_id_users'), 'user_group_members', type_='foreignkey')
    op.alter_column('user_group_members', 'updated_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.alter_column('user_group_members', 'created_at',
               existing_type=sa.DATETIME(),
               nullable=True)
    op.drop_column('cycle_counts', 'transacted_only')
    # ### end Alembic commands ###
